### ISSUE TITLE
Implement Enumerable for Canvas

### ISSUE THREAD

**Issue by watzon** [l3kn/stumpy_core#11]
Seeing as it already supports a lot of the methods anyway, it would be nice to have access to others like `map_with_index` which is the one I'm particularly in need of right now. Also the ability to set a pixel by index instead of with `x, y` coordinates would be nice.

**Comment by l3kn** [comment]
Most of this should be possible by accessing the slice of pixels through `canvas.pixels`,
but I see your point, implementing `Enumerable` would get us a lot of functionality for very little effort.

Regarding `map_with_index`, I think a mutating variant `map_with_index!` would be useful, too.
This is not part of `Enumerable` and implemented for “by hand” for all relevant classes (`Array`, `Slice`, `Pointer`).

The `Array` class [implements a bunch of other mutating functions](https://crystal-lang.org/api/0.29.0/Array.html#map_with_index%21%28%26block%3AT%2CInt32->T%29-instance-method), do you think it would make sense to implement any of these, besides `map!` and `map_with_index!`?

**Comment by watzon** [comment]
It would probably make sense to implement all of them, but the main one I wanted was `map_with_index`

**Comment by l3kn** [comment]
I've started to working on this but I've run into a small problem.

Would you expect `canvas.map_with_index` to return a new `Canvas`?
That's what the current implementation of `canvas.map` does.

When implementing `Enumerable`, `canvas.map` would have to return an array of `RGBA` pixels.

That's unfortunate, but I think to avoid introducing breaking changes,
`map_with_index` and `map_with_index!` should be implemented in the same way as the old `map` and `map!` without implementing `Enumerable` for `Canvas`.

Another problem is that `canvas.map` passes three parameters to the block,
`{ |color, x, y| ...}`. I'm not sure how that should work for `map_with_index`,
it could pass either `{ |color, index| ... }` or `{|color, x, y, index| ... }`.

For working with a raw slice of pixels, `canva.pixels` can be used and already implements `Enumerable`
(because it is a `Slice(RGBA)`

**Comment by watzon** [comment]
I think that `map_with_index` and `map_with_index!` should both work exactly like `map` and `map!`, just with the index added on. I feel like that would be expected behavior.

**Comment by l3kn** [comment]
I've pushed a version with these changes (`v1.9.0`),
let me know if that is working as you'd expect it to.
